# Generated by Django 5.2.17 on 2026-09-24 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('additional_exercise', 'Additional exercise'), ('foundational_exercise', 'Foundational exercise'), ('progress', 'Progress')], max_length=32)),
                ('reason_code', models.CharField(max_length=64)),
                ('input_snapshot_json', models.JSONField(default=dict)),
                ('support_cutoff', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='learning.session')),
            ],
            options={
                'db_table': 'adaptive_decision',
            },
        ),
        migrations.CreateModel(
            name='DecisionTargetSkill',
            fields=[
                ('pk', models.CompositePrimaryKey('decision', 'skill', 'target_kind', blank=True, editable=False, primary_key=True, serialize=False)),
                ('target_kind', models.CharField(choices=[('next_exercise', 'Next exercise'), ('follow_up', 'Follow-up')], max_length=16)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_skills', to='adaptive.decision')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_targets', to='curriculum.skill')),
            ],
            options={
                'db_table': 'adaptive_decision_target_skill',
            },
        ),
        migrations.CreateModel(
            name='SkillMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p_known', models.DecimalField(decimal_places=4, max_digits=5)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_masteries', to='curriculum.skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adaptive_skill_mastery',
            },
        ),
        migrations.CreateModel(
            name='MasteryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p_before', models.DecimalField(decimal_places=4, max_digits=5)),
                ('p_after_observation', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('p_after_learning', models.DecimalField(decimal_places=4, max_digits=5)),
                ('learning_transition_applied', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='mastery_event', to='learning.response')),
                ('mastery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='adaptive.skillmastery')),
            ],
            options={
                'db_table': 'adaptive_mastery_event',
            },
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['action', 'created_at'], name='decision_action_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['additional_exercise', 'foundational_exercise', 'progress'])), name='decision_action_valid'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('reason_code', ''), _negated=True), name='decision_reason_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.CheckConstraint(condition=models.Q(('support_cutoff__gte', 0), ('support_cutoff__lte', 1)), name='decision_cutoff_valid'),
        ),
        migrations.AddIndex(
            model_name='decisiontargetskill',
            index=models.Index(fields=['target_kind', 'skill'], name='decision_target_kind_skill_idx'),
        ),
        migrations.AddConstraint(
            model_name='decisiontargetskill',
            constraint=models.CheckConstraint(condition=models.Q(('target_kind__in', ['next_exercise', 'follow_up'])), name='decision_target_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='decisiontargetskill',
            constraint=models.UniqueConstraint(fields=('decision', 'skill', 'target_kind'), name='decision_target_unique'),
        ),
        migrations.AddIndex(
            model_name='skillmastery',
            index=models.Index(fields=['student', 'skill'], name='mastery_student_skill_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillmastery',
            constraint=models.UniqueConstraint(fields=('student', 'skill'), name='mastery_student_skill_unique'),
        ),
        migrations.AddConstraint(
            model_name='skillmastery',
            constraint=models.CheckConstraint(condition=models.Q(('p_known__gte', 0), ('p_known__lte', 1)), name='mastery_p_known_valid'),
        ),
        migrations.AddConstraint(
            model_name='skillmastery',
            constraint=models.CheckConstraint(condition=models.Q(('evidence_count__gte', 0)), name='mastery_evidence_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='masteryevent',
            index=models.Index(fields=['mastery', 'created_at'], name='event_mastery_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='masteryevent',
            constraint=models.CheckConstraint(condition=models.Q(('p_before__gte', 0), ('p_before__lte', 1)), name='event_p_before_valid'),
        ),
        migrations.AddConstraint(
            model_name='masteryevent',
            constraint=models.CheckConstraint(condition=models.Q(('p_after_observation__isnull', True), models.Q(('p_after_observation__gte', 0), ('p_after_observation__lte', 1)), _connector='OR'), name='event_p_observation_valid'),
        ),
        migrations.AddConstraint(
            model_name='masteryevent',
            constraint=models.CheckConstraint(condition=models.Q(('p_after_learning__gte', 0), ('p_after_learning__lte', 1)), name='event_p_learning_valid'),
        ),
    ]
