# Generated by Django 5.2.17 on 2026-09-24 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('pretest', 'Pre-test'), ('regular', 'Regular'), ('additional', 'Additional'), ('foundational', 'Foundational'), ('activity', 'Activity'), ('posttest', 'Post-test')], max_length=16)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='issued', max_length=16)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_sessions', to='curriculum.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learning_session',
            },
        ),
        migrations.CreateModel(
            name='SessionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_items', to='curriculum.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='learning.session')),
            ],
            options={
                'db_table': 'learning_session_item',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hint_used', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField()),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='curriculum.questionchoice')),
                ('session_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='learning.sessionitem')),
            ],
            options={
                'db_table': 'learning_response',
            },
        ),
        migrations.CreateModel(
            name='StudentPath',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='learning_path', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('pretest_required', 'Pre-test required'), ('learning', 'Learning'), ('activity_ready', 'Activity ready'), ('posttest_ready', 'Post-test ready'), ('completed', 'Completed')], max_length=24)),
                ('current_stage', models.CharField(choices=[('pretest', 'Pre-test'), ('lesson', 'Lesson'), ('regular', 'Regular'), ('additional', 'Additional'), ('foundational', 'Foundational'), ('activity', 'Activity'), ('posttest', 'Post-test')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_student_paths', to='curriculum.lesson')),
            ],
            options={
                'db_table': 'learning_student_path',
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['student', 'status', 'created_at'], name='sess_student_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['student', 'session_type', 'lesson'], name='sess_student_type_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_type', 'completed_at'], name='session_type_completed_idx'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('session_type__in', ['pretest', 'regular', 'additional', 'foundational', 'activity', 'posttest'])), name='session_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['issued', 'in_progress', 'submitted', 'completed'])), name='session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gt', 0)), name='session_attempt_positive'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('session_type__in', ['regular', 'additional', 'foundational'])), models.Q(('lesson__isnull', True), ('session_type__in', ['pretest', 'activity', 'posttest'])), _connector='OR'), name='session_lesson_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('started_at__isnull', True), ('status', 'issued'), ('submitted_at__isnull', True)), models.Q(('completed_at__isnull', True), ('started_at__isnull', False), ('status', 'in_progress'), ('submitted_at__isnull', True)), models.Q(('completed_at__isnull', True), ('started_at__isnull', False), ('status', 'submitted'), ('submitted_at__isnull', False)), models.Q(('completed_at__isnull', False), ('started_at__isnull', False), ('status', 'completed'), ('submitted_at__isnull', False)), _connector='OR'), name='session_status_timestamps_valid'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('submitted_at__isnull', True), ('submitted_at__gte', models.F('started_at')), _connector='OR'), name='session_submitted_order_valid'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__isnull', True), ('completed_at__gte', models.F('submitted_at')), _connector='OR'), name='session_completed_order_valid'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', False)), fields=('student', 'session_type', 'lesson', 'attempt_number'), name='session_lesson_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson__isnull', True)), fields=('student', 'session_type', 'attempt_number'), name='session_course_attempt_unique'),
        ),
        migrations.AddIndex(
            model_name='sessionitem',
            index=models.Index(fields=['session', 'display_order'], name='session_item_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='session_item_question_unique'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.UniqueConstraint(fields=('session', 'display_order'), name='session_item_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='sessionitem',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__gt', 0)), name='session_item_order_positive'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['answered_at'], name='response_answered_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpath',
            index=models.Index(fields=['status', 'current_stage'], name='student_path_status_stage_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpath',
            index=models.Index(fields=['updated_at'], name='student_path_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentpath',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pretest_required', 'learning', 'activity_ready', 'posttest_ready', 'completed'])), name='student_path_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='studentpath',
            constraint=models.CheckConstraint(condition=models.Q(('current_stage__in', ['pretest', 'lesson', 'regular', 'additional', 'foundational', 'activity', 'posttest'])), name='student_path_stage_valid'),
        ),
    ]
