# Generated by Django 5.2.17 on 2026-09-24 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('lesson_order', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content_json', models.JSONField(default=list)),
                ('content_schema_version', models.PositiveSmallIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_lesson',
                'indexes': [models.Index(fields=['is_published', 'lesson_order'], name='lesson_published_order_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('lesson_order__gt', 0)), name='lesson_order_positive'), models.CheckConstraint(condition=models.Q(('content_schema_version__gt', 0)), name='lesson_schema_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('p_l0', models.DecimalField(decimal_places=4, max_digits=5)),
                ('p_t', models.DecimalField(decimal_places=4, max_digits=5)),
                ('p_g', models.DecimalField(decimal_places=4, max_digits=5)),
                ('p_s', models.DecimalField(decimal_places=4, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_skill',
                'constraints': [models.CheckConstraint(condition=models.Q(('p_l0__gte', 0), ('p_l0__lte', 1)), name='skill_p_l0_valid'), models.CheckConstraint(condition=models.Q(('p_t__gte', 0), ('p_t__lte', 1)), name='skill_p_t_valid'), models.CheckConstraint(condition=models.Q(('p_g__gte', 0), ('p_g__lte', 1)), name='skill_p_g_valid'), models.CheckConstraint(condition=models.Q(('p_s__gte', 0), ('p_s__lte', 1)), name='skill_p_s_valid')],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('set_type', models.CharField(choices=[('prepost', 'Pre/post'), ('regular', 'Regular'), ('additional', 'Additional'), ('foundational', 'Foundational'), ('activity', 'Activity')], max_length=16)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_sets', to='curriculum.lesson')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_sets', to='curriculum.skill')),
            ],
            options={
                'db_table': 'curriculum_question_set',
            },
        ),
        migrations.CreateModel(
            name='LessonSkill',
            fields=[
                ('pk', models.CompositePrimaryKey('lesson', 'skill', blank=True, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_skills', to='curriculum.lesson')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_skills', to='curriculum.skill')),
            ],
            options={
                'db_table': 'curriculum_lesson_skill',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('youtube_video_id', models.CharField(max_length=32, unique=True)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('transcript', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'curriculum_video',
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0)), name='video_duration_positive'), models.CheckConstraint(condition=models.Q(('transcript', ''), _negated=True), name='video_transcript_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('prompt', models.TextField()),
                ('difficulty', models.CharField(choices=[('standard', 'Standard'), ('foundational', 'Foundational')], max_length=16)),
                ('presentation_type', models.CharField(choices=[('text', 'Text'), ('figure', 'Figure'), ('video', 'Video')], max_length=16)),
                ('cognitive_level', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyze', 'Analyze'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=16)),
                ('solution_steps_json', models.JSONField(default=list)),
                ('explanation', models.TextField()),
                ('hint', models.TextField(blank=True, null=True)),
                ('feedback_correct', models.TextField()),
                ('feedback_incorrect', models.TextField()),
                ('image_asset', models.CharField(blank=True, max_length=255, null=True)),
                ('image_alt', models.TextField(blank=True, null=True)),
                ('visual_component', models.CharField(blank=True, max_length=128, null=True)),
                ('visual_config_json', models.JSONField(blank=True, null=True)),
                ('video_pause_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.skill')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='curriculum.video')),
            ],
            options={
                'db_table': 'curriculum_question',
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('misconception_code', models.CharField(blank=True, max_length=64, null=True)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='curriculum.question')),
            ],
            options={
                'db_table': 'curriculum_question_choice',
                'constraints': [models.CheckConstraint(condition=models.Q(('label__in', ['A', 'B', 'C', 'D'])), name='choice_label_valid'), models.CheckConstraint(condition=models.Q(('display_order__range', (1, 4))), name='choice_order_valid'), models.UniqueConstraint(fields=('question', 'label'), name='choice_question_label_unique'), models.UniqueConstraint(fields=('question', 'display_order'), name='choice_question_order_unique'), models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question',), name='choice_one_correct')],
            },
        ),
        migrations.CreateModel(
            name='QuestionSetItem',
            fields=[
                ('pk', models.CompositePrimaryKey('question_set', 'question', blank=True, editable=False, primary_key=True, serialize=False)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_items', to='curriculum.question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curriculum.questionset')),
            ],
            options={
                'db_table': 'curriculum_question_set_item',
                'constraints': [models.UniqueConstraint(fields=('question_set', 'question'), name='qset_item_question_unique'), models.UniqueConstraint(fields=('question_set', 'display_order'), name='qset_item_order_unique'), models.CheckConstraint(condition=models.Q(('display_order__gt', 0)), name='qset_item_order_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(fields=['set_type', 'is_published'], name='qset_type_published_idx'),
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(fields=['lesson'], name='qset_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='questionset',
            index=models.Index(fields=['skill'], name='qset_skill_idx'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(condition=models.Q(('set_type__in', ['prepost', 'regular', 'additional', 'foundational', 'activity'])), name='question_set_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='questionset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lesson__isnull', False), ('set_type__in', ['regular', 'additional']), ('skill__isnull', True)), models.Q(('lesson__isnull', True), ('set_type', 'foundational'), ('skill__isnull', False)), models.Q(('lesson__isnull', True), ('set_type__in', ['prepost', 'activity']), ('skill__isnull', True)), _connector='OR'), name='question_set_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='lessonskill',
            constraint=models.UniqueConstraint(fields=('lesson', 'skill'), name='lesson_skill_unique'),
        ),
        migrations.AddConstraint(
            model_name='lessonskill',
            constraint=models.UniqueConstraint(fields=('lesson', 'display_order'), name='lesson_skill_order_unique'),
        ),
        migrations.AddConstraint(
            model_name='lessonskill',
            constraint=models.CheckConstraint(condition=models.Q(('display_order__in', [1, 2])), name='lesson_skill_order_valid'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['skill', 'is_published'], name='question_skill_published_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['presentation_type', 'is_published'], name='question_media_published_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['difficulty'], name='question_difficulty_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty__in', ['standard', 'foundational'])), name='question_difficulty_valid'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('presentation_type__in', ['text', 'figure', 'video'])), name='question_presentation_valid'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('cognitive_level__in', ['remember', 'understand', 'apply', 'analyze', 'evaluate', 'create'])), name='question_cognitive_valid'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('difficulty', 'foundational'), ('hint__isnull', True), _connector='OR'), name='question_hint_valid'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_alt__isnull', True), ('image_asset__isnull', True), ('presentation_type', 'text'), ('video__isnull', True), ('video_pause_seconds__isnull', True), ('visual_component__isnull', True), ('visual_config_json__isnull', True)), models.Q(('image_alt__isnull', False), ('presentation_type', 'figure'), ('video__isnull', True), ('video_pause_seconds__isnull', True), models.Q(('image_alt', ''), _negated=True), models.Q(models.Q(('image_asset__isnull', False), ('visual_component__isnull', True), ('visual_config_json__isnull', True)), models.Q(('image_asset__isnull', True), ('visual_component__isnull', False), ('visual_config_json__isnull', False)), _connector='OR')), models.Q(('image_alt__isnull', True), ('image_asset__isnull', True), ('presentation_type', 'video'), ('video__isnull', False), ('video_pause_seconds__isnull', False), ('visual_component__isnull', True), ('visual_config_json__isnull', True), ('video_pause_seconds__gt', 0)), _connector='OR'), name='question_media_shape_valid'),
        ),
    ]
