# Generated by Django 5.2.17 on 2026-09-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_question_video_cue_trigger'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='question_media_shape_valid',
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image_alt__isnull', True), ('image_asset__isnull', True), ('presentation_type', 'text'), ('video__isnull', True), ('video_pause_seconds__isnull', True), ('visual_component__isnull', True), ('visual_config_json__isnull', True)), models.Q(('image_alt__isnull', False), ('presentation_type', 'figure'), ('video__isnull', True), ('video_pause_seconds__isnull', True), models.Q(('image_alt', ''), _negated=True), models.Q(models.Q(('image_asset__isnull', False), ('visual_component__isnull', True), ('visual_config_json__isnull', True), models.Q(('image_asset', ''), _negated=True)), models.Q(('image_asset__isnull', True), ('visual_component__isnull', False), ('visual_config_json__isnull', False), models.Q(('visual_component', ''), _negated=True)), _connector='OR')), models.Q(('image_alt__isnull', True), ('image_asset__isnull', True), ('presentation_type', 'video'), ('video__isnull', False), ('video_pause_seconds__isnull', False), ('visual_component__isnull', True), ('visual_config_json__isnull', True), ('video_pause_seconds__gt', 0)), _connector='OR'), name='question_media_shape_valid'),
        ),
    ]
