# Generated by Django 5.2.17 on 2026-09-24 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=128)),
                ('target_id', models.UUIDField()),
                ('target_snapshot_json', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True, null=True)),
                ('metadata_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_audit_event',
                'indexes': [models.Index(fields=['created_at'], name='audit_created_idx'), models.Index(fields=['action', 'created_at'], name='audit_action_created_idx'), models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_lookup_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action', ''), _negated=True), name='audit_action_nonblank'), models.CheckConstraint(condition=models.Q(('target_type', ''), _negated=True), name='audit_target_type_nonblank')],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('study_access_enabled', models.BooleanField(default=True)),
                ('posttest_access_enabled', models.BooleanField(default=False)),
                ('changed_at', models.DateTimeField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='system_setting_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_system_setting',
                'constraints': [models.CheckConstraint(condition=models.Q(('singleton_key', 1)), name='setting_singleton_key_valid'), models.CheckConstraint(condition=models.Q(('revision__gte', 0)), name='setting_revision_nonnegative')],
            },
        ),
    ]
