# Generated by Django 5.2.17 on 2026-09-24 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('generation_status', models.CharField(choices=[('generated', 'Generated'), ('fallback', 'Fallback')], max_length=16)),
                ('model_name', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to='learning.session')),
            ],
            options={
                'db_table': 'feedback_session_feedback',
                'indexes': [models.Index(fields=['generation_status', 'created_at'], name='feedback_status_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('generation_status__in', ['generated', 'fallback'])), name='feedback_status_valid'), models.CheckConstraint(condition=models.Q(('feedback_text', ''), _negated=True), name='feedback_text_nonblank'), models.CheckConstraint(condition=models.Q(models.Q(('generation_status', 'generated'), ('model_name', 'gpt-oss-120b')), models.Q(('generation_status', 'fallback'), ('model_name__isnull', True)), _connector='OR'), name='feedback_model_status_valid')],
            },
        ),
    ]
