# Generated by Django 5.2.17 on 2026-09-24 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archive_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_classrooms', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taught_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classrooms_classroom',
            },
        ),
        migrations.CreateModel(
            name='StudentMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_student_memberships', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_memberships', to='classrooms.classroom')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_student_memberships', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classrooms_student_membership',
            },
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['teacher', 'status'], name='classroom_teacher_status_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['status'], name='classroom_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'archived'])), name='classroom_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archive_reason__isnull', True), ('archived_at__isnull', True), ('archived_by__isnull', True), ('status', 'active')), models.Q(('archive_reason__isnull', False), ('archived_at__isnull', False), ('archived_by__isnull', False), ('status', 'archived'), models.Q(('archive_reason', ''), _negated=True)), _connector='OR'), name='classroom_archive_valid'),
        ),
        migrations.AddIndex(
            model_name='studentmembership',
            index=models.Index(fields=['classroom', 'left_at'], name='membership_class_open_idx'),
        ),
        migrations.AddIndex(
            model_name='studentmembership',
            index=models.Index(fields=['student', 'left_at'], name='membership_student_open_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('classroom', 'student'), name='membership_one_open'),
        ),
        migrations.AddConstraint(
            model_name='studentmembership',
            constraint=models.CheckConstraint(condition=models.Q(('left_at__isnull', True), ('left_at__gte', models.F('joined_at')), _connector='OR'), name='membership_dates_valid'),
        ),
    ]
